#/bin/sh
# APP_LOCATION must be the appengine_staging directory of the app
# RUNTIME_LOCATION is the directory containing the 3 runtime jars for ex
#

# curl https://repo1.maven.org/maven2/com/google/appengine/runtime-deployment/2.0.9/runtime-deployment-2.0.9.zip -o runtime-deployment-2.0.9.zip

set -x

# Location of appengine-java-standard project.
APPENGINE_JAVA_STANDARD="/home/lachlan/webtide/appengine-java-standard"

# This is generated by using `mvn clean package appengine:stage` command in root of the webapp project.
APP_LOCATION=/home/lachlan/webtide/appengine-performance-testing/target/appengine-staging

RUNTIME_DEPLOYMENT="/tmp/runtime-deployment"
mkdir -p $RUNTIME_DEPLOYMENT
rm -rf ${RUNTIME_DEPLOYMENT:?}/*
cp /home/lachlan/webtide/appengine-performance-testing/src/main/runtime-deployment/runtime-* $RUNTIME_DEPLOYMENT

# To start API Server you run this from root of appengine-java-standard repository.
# mvn exec:java -pl :appengine-apis-dev -Dexec.mainClass="com.google.appengine.tools.development.HttpApiServer"

"$JAVA_HOME"/bin/java \
 --add-opens java.base/java.lang=ALL-UNNAMED \
 --add-opens java.base/java.nio.charset=ALL-UNNAMED \
 --add-opens java.logging/java.util.logging=ALL-UNNAMED \
 --add-opens java.base/java.util.concurrent=ALL-UNNAMED \
 -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000 \
 -showversion -XX:+PrintCommandLineFlags \
 -Djava.class.path=$RUNTIME_DEPLOYMENT/runtime-main.jar \
 -Dclasspath.runtimebase=$RUNTIME_DEPLOYMENT: \
 com/google/apphosting/runtime/JavaRuntimeMainWithDefaults \
 --fixed_application_path=$APP_LOCATION  \
 $RUNTIME_DEPLOYMENT
