apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-1
  namespace: bench
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: load-master
          image: jettyproject/jetty-appengine-ssh:30-04-2024-21-25
          resources:
            limits:
              memory: "6Gi"
              cpu: "1000m"
            requests:
              memory: "4Gi"
              cpu: "700m"
          ports:
            - containerPort: 22

apiVersion: v1
kind: Service
metadata:
  name: load-1
  namespace: bench
spec:
  type: LoadBalancer  
  ports:
    - name: ssh-port
      port: 22
      targetPort: 22
      nodePort: 30000 

